# coding: utf-8

"""
    FINBOURNE Luminesce Web API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from luminesce.models.background_query_state import BackgroundQueryState

class BackgroundQueryListItem(BaseModel):
    """
    A background query the calling user currently has available to them  # noqa: E501
    """
    execution_id:  Optional[StrictStr] = Field(None,alias="executionId", description="ExecutionId of the query") 
    query:  Optional[StrictStr] = Field(None,alias="query", description="The LuminesceSql of the original request") 
    query_name:  Optional[StrictStr] = Field(None,alias="queryName", description="The QueryName given in the original request") 
    state: Optional[BackgroundQueryState] = None
    when: Optional[datetime] = Field(default=None, description="When the state of this query (and so its data) was last updated (UTC)")
    expires_at: Optional[datetime] = Field(default=None, description="When the query (and its data) may be removed (UTC)", alias="expiresAt")
    __properties = ["executionId", "query", "queryName", "state", "when", "expiresAt"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BackgroundQueryListItem:
        """Create an instance of BackgroundQueryListItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if execution_id (nullable) is None
        # and __fields_set__ contains the field
        if self.execution_id is None and "execution_id" in self.__fields_set__:
            _dict['executionId'] = None

        # set to None if query (nullable) is None
        # and __fields_set__ contains the field
        if self.query is None and "query" in self.__fields_set__:
            _dict['query'] = None

        # set to None if query_name (nullable) is None
        # and __fields_set__ contains the field
        if self.query_name is None and "query_name" in self.__fields_set__:
            _dict['queryName'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BackgroundQueryListItem:
        """Create an instance of BackgroundQueryListItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BackgroundQueryListItem.parse_obj(obj)

        _obj = BackgroundQueryListItem.parse_obj({
            "execution_id": obj.get("executionId"),
            "query": obj.get("query"),
            "query_name": obj.get("queryName"),
            "state": obj.get("state"),
            "when": obj.get("when"),
            "expires_at": obj.get("expiresAt")
        })
        return _obj

BackgroundQueryListItem.update_forward_refs()
