# coding: utf-8

"""
    FINBOURNE Luminesce Web API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg

from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime


class ExportType(str, Enum):
    """
    The types of Exporting capable of being delivered by the WebAPI. Similar but not identical to <seealso cref=\"T:Finbourne.Honeycomb.Api.Hosting.Exporting.OutputType\" />
    """

    """
    allowed enum values
    """
    CSV = 'csv'
    PIPE = 'pipe'
    EXCEL = 'excel'
    JSON = 'json'
    JSONPROPER = 'jsonProper'
    XML = 'xml'
    PARQUET = 'parquet'
    SQLITE = 'sqlite'
    TABLEINTERNAL = 'TableInternal'
    JSONPROPERWITHLINEAGE = 'jsonProperWithLineage'
    PDF = 'pdf'

    @classmethod
    def from_json(cls, json_str: str) -> ExportType:
        """Create an instance of ExportType from a JSON string"""
        return ExportType(json.loads(json_str))
