# coding: utf-8

"""
    FINBOURNE Luminesce Web API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime

class ViewItem(BaseModel):
    """
    ViewItem
    """
    name:  Optional[StrictStr] = Field(None,alias="name", description="The name of the view") 
    domain:  Optional[StrictStr] = Field(None,alias="domain", description="The domain the view applies to") 
    file_path:  Optional[StrictStr] = Field(None,alias="filePath", description="The full file path in the HcFs") 
    file_content:  Optional[StrictStr] = Field(None,alias="fileContent", description="The full file content in the HcFs. This will be needed for Upserting the view to a different domain / for use in fbn-config.") 
    last_updated_execution_id:  Optional[StrictStr] = Field(None,alias="lastUpdatedExecutionId", description="The last ExecutionId, needed to get the creating Sql out of the logs") 
    last_updated_at: Optional[datetime] = Field(default=None, description="The last updated at time, needed to get the creating Sql out of the logs", alias="lastUpdatedAt")
    last_updated_by:  Optional[StrictStr] = Field(None,alias="lastUpdatedBy", description="The last updated by this user") 
    created_by_user_id:  Optional[StrictStr] = Field(None,alias="createdByUserId", description="Originally created by this user") 
    __properties = ["name", "domain", "filePath", "fileContent", "lastUpdatedExecutionId", "lastUpdatedAt", "lastUpdatedBy", "createdByUserId"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ViewItem:
        """Create an instance of ViewItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if name (nullable) is None
        # and __fields_set__ contains the field
        if self.name is None and "name" in self.__fields_set__:
            _dict['name'] = None

        # set to None if domain (nullable) is None
        # and __fields_set__ contains the field
        if self.domain is None and "domain" in self.__fields_set__:
            _dict['domain'] = None

        # set to None if file_path (nullable) is None
        # and __fields_set__ contains the field
        if self.file_path is None and "file_path" in self.__fields_set__:
            _dict['filePath'] = None

        # set to None if file_content (nullable) is None
        # and __fields_set__ contains the field
        if self.file_content is None and "file_content" in self.__fields_set__:
            _dict['fileContent'] = None

        # set to None if last_updated_execution_id (nullable) is None
        # and __fields_set__ contains the field
        if self.last_updated_execution_id is None and "last_updated_execution_id" in self.__fields_set__:
            _dict['lastUpdatedExecutionId'] = None

        # set to None if last_updated_at (nullable) is None
        # and __fields_set__ contains the field
        if self.last_updated_at is None and "last_updated_at" in self.__fields_set__:
            _dict['lastUpdatedAt'] = None

        # set to None if last_updated_by (nullable) is None
        # and __fields_set__ contains the field
        if self.last_updated_by is None and "last_updated_by" in self.__fields_set__:
            _dict['lastUpdatedBy'] = None

        # set to None if created_by_user_id (nullable) is None
        # and __fields_set__ contains the field
        if self.created_by_user_id is None and "created_by_user_id" in self.__fields_set__:
            _dict['createdByUserId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ViewItem:
        """Create an instance of ViewItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ViewItem.parse_obj(obj)

        _obj = ViewItem.parse_obj({
            "name": obj.get("name"),
            "domain": obj.get("domain"),
            "file_path": obj.get("filePath"),
            "file_content": obj.get("fileContent"),
            "last_updated_execution_id": obj.get("lastUpdatedExecutionId"),
            "last_updated_at": obj.get("lastUpdatedAt"),
            "last_updated_by": obj.get("lastUpdatedBy"),
            "created_by_user_id": obj.get("createdByUserId")
        })
        return _obj

ViewItem.update_forward_refs()
